
CREATE TABLE public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  "salaryTier" text NOT NULL,
  "salaryRange" text NOT NULL,
  question text NOT NULL,
  options jsonb NOT NULL,
  "correctAnswers" jsonb NOT NULL,
  "multipleCorrect" boolean NOT NULL DEFAULT false,
  hint text NOT NULL,
  explanation text NOT NULL,
  tier smallint NOT NULL DEFAULT 1,
  difficulty smallint NOT NULL DEFAULT 1,
  source text NOT NULL DEFAULT '',
  "flagCount" integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true
);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active questions"
  ON public.questions FOR SELECT USING (active = true);

CREATE POLICY "Admins can insert questions"
  ON public.questions FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can update questions"
  ON public.questions FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can delete questions"
  ON public.questions FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can read all questions"
  ON public.questions FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));
